# Generated by Django 3.0.2 on 2021-06-03 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('party', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('pic', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='debate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('duration', models.IntegerField()),
                ('voice_location', models.TextField()),
                ('defense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offense', to='votedb.candidate')),
                ('pros', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pros', to='votedb.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='login_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='state_info',
            fields=[
                ('state', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('state_abbr', models.CharField(max_length=20)),
                ('state_vote_num', models.IntegerField()),
                ('has_votes_right_population', models.IntegerField()),
                ('in_votes_ages_population', models.IntegerField()),
                ('prisoner_population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.IntegerField()),
                ('text', models.TextField()),
                ('likes', models.IntegerField()),
                ('retweet', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('user_screen_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_like_tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tweet_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='state_total_vote',
            fields=[
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='votedb.state_info')),
                ('votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=40)),
                ('authority', models.IntegerField()),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votedb.state_info')),
                ('voted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='votedb.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='state_vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField()),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votedb.candidate')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votedb.state_info')),
            ],
        ),
        migrations.CreateModel(
            name='history_vote_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_year', models.IntegerField()),
                ('party', models.CharField(max_length=20)),
                ('votes', models.IntegerField()),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votedb.state_info')),
            ],
            options={
                'db_tablespace': 'tables',
            },
        ),
        migrations.CreateModel(
            name='debate_script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('speaker', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time_stamp', models.IntegerField()),
                ('debate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votedb.debate')),
            ],
        ),
    ]
